### ISSUE TITLE
sent_from: Fuzzy matching issue

### ISSUE THREAD

**Issue by luke-hill** [mailosaur/mailosaur-ruby#35]
When using the `sent_from` input arg and `match` "ALL" observe the following.

```
**VALID**
#<Mailosaur::Models::SearchCriteria:0x0000559f9b271678 @sent_from="citizensadvice.org.uk", @sent_to="test312.nobody.5nkqao7i@mailosaur.io", @subject=nil, @body=nil, @match="ALL">

**VALID**
#<Mailosaur::Models::SearchCriteria:0x0000559f9b271678 @sent_from="JEFF@citizensadvice.org.uk", @sent_to="test312.nobody.5nkqao7i@mailosaur.io", @subject=nil, @body=nil, @match="ALL">

**INVALID**
#<Mailosaur::Models::SearchCriteria:0x0000559f9b271678 @sent_from="@citizensadvice.org.uk", @sent_to="test312.nobody.5nkqao7i@mailosaur.io", @subject=nil, @body=nil, @match="ALL">
```
This is likely matching taking place detecting that an e-mail address can't start with an `@` but if you're using fuzzy matching, this validation needs removing.

**Comment by hippyhorse** [comment]
@luke-hill This issue hasn't been addressed for quite some time, could you confirm if this is still an issue?

**Comment by luke-hill** [comment]
I've just got set up with mailosaur, so give me another 1-2 weeks and I can confirm/deny

**Comment by hippyhorse** [comment]
@luke-hill closing this one for now, if you find this is still an issue please do reopen or contact support 👍
